#+TITLE:     Reference checker
#+AUTHOR:    Ryan Whittingham
#+EMAIL:     (concat "ryanwhittingham89" at-sign "gmail.com")
#+DESCRIPTION: Check academic references in .docx file
#+KEYWORDS:  python, docx
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:2 p:t

This repository provides scripts that can allow you to validate
academic references in a .docx file using the =python-docx= package.

* Requirements

- Python 3
- =python-docx=
- =ansi2html=
- =git=

** Optional requirements

- Golang

* Usage

If you have Go installed, you can run the main server with =go run
./server.go=. Navigate to localhost:8000 in a browser, and enjoy.
Alternatively, you may call =docx_refs.sh= -- a wrapper around
=docx_refs.py= -- from the command line. Note that =./docx_refs.py=
will *overwrite* your original file, so you probably don't want to
call it directly. In any case, you'll receive an HTML document back
telling you whether any of your references are out of order.

* TODO Things to do

- Determine whether citations are missing from references list
- Determine whether references list has extraneous citations
